### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by davehorton** [signalwire/freeswitch#110]
Could you add a LICENSE file to the top level of the repo so it is clear what license governs the use and distribution of this code base?

**Comment by mjerris** [comment]
this is best documented in the debian license files currently

**Comment by ITwrx** [comment]
@mjerris why would it be more appropriate to document this code's license in one down stream distro instead of the upstream repo for the project?

**Comment by ITwrx** [comment]
@mjerris 
i see now that the "Debian package" is a FreeSWITCH packaged and released .deb. Not a Debian packaged and released .deb. 

What is the text of (or link to) the license you alluded to? 

i don't have a Debian based distro to download and inspect with, and when i search for "license" on the FreeSWITCH server for these debs i find:

```
 freeswitch-license-server
This package contains the FreeSWITCH
 Software License Control Server and
 License Validator.

```
This sounds like proprietary software to me.

Is FreeSWITCH F/OSS in some way i'm not seeing? Or is it actually proprietary, cross-platform? 

Because if the source a user receives doesn't have a license, that is proprietary by default.
https://choosealicense.com/no-permission/

Thanks

**Comment by hex-m** [comment]
There is a [copyright file](https://github.com/signalwire/freeswitch/blob/master/debian/copyright) stating that it's Mozilla Public License 1.1. MPL 1.1 is also mentioned in the header of the source files.

Making the license more visible the way it's [usually done](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) on GitHub is still a good idea imo.

**Comment by crienzo** [comment]
Added
