### ISSUE TITLE
Check whether the H323 module supports the SIP video call function?

### ISSUE THREAD

**Issue by 1205469665** [signalwire/freeswitch#1433]
Check whether the H323 module supports the SIP video call function?
According to the way provided by the official website to try, only dial can not video. Also can support H323 to participate in video conference

**Comment by seven1240** [comment]
h323 modules in tree was developed before FreeSWITCH has full video support. We have a private module with basic video support.

**Comment by 1205469665** [comment]
Which module do you support? Is this the h323 that doesn't support video? Which module are you talking about for SIP? Do you have one for 323?

**Comment by 1205469665** [comment]
I'm trying to make a video call to h323 via Freeswitch. Is that possible with that private module, which module?

**Comment by seven1240** [comment]
Private means not publicly available. Both modules in tree depends on libs which are too old and doesn't even work on morden OSes. gnugk has the same problem.

H323 is a dying protocol and no one want to invest on it. Though someone asks for it occasionally, it's not enough to sponsor the development. People just want to use the legacy devices since they were expensive. And I don't even have a device to test. Maybe it's best to throw all the legacy deices and let is die faster and so the whole world can use SIP. I like the H323 protocol and would like to make it work but while it can it too hard. Contact me if you or someone else would like to sponsor the development. The last time I talked to someone asking H323 I got some response like: Go  to hell, I don't want to pay you for a dying protocol. I just want it work. 🤷

**Comment by manikantavarikuppala** [comment]
can i use H323 for making video call via freeswitch i searched for it alot. But couldn't find any and in some websites it shows h323 doesn't support video and the freeswitch thinks the video codec as audio codec. Is there any other way that i can use H323 as video for freeswitch? @seven1240
