### ISSUE TITLE
Sofia SIP compilation error, what's wrong?

### ISSUE THREAD

**Issue by vinson2025** [signalwire/freeswitch#1761]
OS is Debian11.4. Sofia-sip has come from "git clone https://github.com/freeswitch/sofia-sip".  downloaded all over, then input command:  cd Sofia-sip, ./bootstrap.sh appear an error:

![image](https://user-images.githubusercontent.com/77615677/184086271-6acfb529-09d1-46a2-a23e-c142828a8ea6.png)

**Comment by mjerris** [comment]
we have packages for sofia-sip.  if you are having issues building it and actually need to, file it in that repo.  otherwise please read our installation documents and follow them as this is the 3rd issue we’ve needed to close of yours in the last 2 days that would have been better solved by following our documents
