### ISSUE TITLE
Feature: disable multiple verto registrations.

### ISSUE THREAD

**Issue by royalpinto** [signalwire/freeswitch#571]
Currently, FreeSWITCH allows an agent to login from multiple Verto clients. This allows an agent account to be shared with multiple agents and misuse the call centre. Also, this leads to confusions to the users.

Hence requesting for a feature to disable multiple sessions from the same account.
I have implemented this feature here: https://github.com/ASWATFZLLC/freeswitch/commit/5066eb62d563cdfe8a911fb2427263619d9b7fdc
It prevents the client to log in if it has already logged in elsewhere. However, there is a corner case for this. When the socket gets disconnected forcefully (like network goes down etc), FreeSWITCH will not come to know instantly about this. It takes about 5 minutes for FreeSWITCH to say that it's disconnected. In this case, If the agent tries to elsewhere, it will say already connected.

Any thoughts on this or any better way to solve this?

**Comment by tessercat** [comment]
I think this is a good idea, as you say, to avoid confusion of duplicate sessions and the potential for misuse.

Regarding the edge case, perhaps checking for the duplicate could be done in `set_session_id` or `attach_jsock` instead of later in `check_auth`. These methods get called in the client thread only on socket init. If there's already a jsock for a user, maybe drop the new one in the same way that `attach_jsock` kills old jsocks when it finds them, essentially by sending a `verto.punt` message to the old jsock and setting `drop` on it so its thread dies.

Note that I'm not a FreeSWITCH developer, so take this with a grain of salt. I've just been reading verto code lately and developing a custom RPC client, and I thought I'd look through the verto bug reports and noticed this good suggestion.

**Comment by tessercat** [comment]
I've added a [feature request](https://github.com/signalwire/freeswitch/issues/832) that I think could also solve this problem in a different way. If a `verto_punt` API command exists, you could add a Lua hook script that listens for login events, checks the output of `verto status` and `verto_punt`s the new login if a client with the same login username already exists.

**Comment by mjerris** [comment]
we'd be happy to review a pull request that implements this
