### ISSUE TITLE
switch_loadable_module.c

### ISSUE THREAD

**Issue by Rustem2313** [signalwire/freeswitch#682]
2020-06-09 13:50:58.464338 [CRIT] switch_loadable_module.c:1785 Error Loading module /usr/lib64/freeswitch/mod/freeswitch.so
**/usr/lib64/freeswitch/mod/freeswitch.so: cannot open shared object file: No such file or directory**
 
zdrastvuyte zacem dayot mne takuyu osibku? kak ispravit eto? spasibo

**Comment by andywolk** [comment]
@Rustem2313 Pishite na angliyskom.
Translation: "Why does it give me such an error? How to fix it? Thanks."

Look at `modules.conf` and see if you have a line containing `freeswitch`. If so then this is wrong because there is no `freeswitch` module. All modules start with `mod_` for example `mod_conference`

I'm closing the issue. 
Also you may ask questions on Slack: http://signalwire.community/
