### ISSUE TITLE
Freeswitch does not reliably send ICE STUN checks

### ISSUE THREAD

**Issue by docfaraday** [signalwire/freeswitch#751]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1654735

Freeswitch seems to require at least four ICE STUN checks to be received before it begins sending ICE STUN checks of its own.

**Comment by mjerris** [comment]
your client is providing no stun discovered candidates only rfc 1918 addresses it appears the server can not route to.  if you fix your client to send the right candidates we will be able to send to them

**Comment by docfaraday** [comment]
When receiving an ICE check from a source that is not yet known, an ICE agent must create what is called a "peer reflexive" candidate:

https://tools.ietf.org/html/rfc8445#section-7.3.1.3

Then, once this new candidate is created, the triggered check logic must happen:

https://tools.ietf.org/html/rfc8445#section-7.3.1.4

If an agent does not perform these steps, an ICE agent will not interoperate with an agent behind a NAT that does endpoint-dependent mapping, even if that agent is not behind a NAT at all.

**Comment by markose** [comment]
Thank you very much for your comments. That was actually the problem. Strangely enough, it worked with Chrome and Freeswitch, since Freeswitch probably changes the destination address for the connectivity checks if the client sends its stun messages aggressively enough, even if no SRFLX candidate was submitted.

**Comment by mjerris** [comment]
yes.. we do "magically" adjust IF we are getting stun requests we assume that this is a valid candidate.  It does take longer but helps misconfigured clients work when they otherwise wouldnt.

**Comment by docfaraday** [comment]
The ICE spec requires you to do this on the first request.

**Comment by markose** [comment]
I've created a patch for switch_rtp.c (Version 1.10.4-release+git~20200805T110119Z~133fc2c870~64bit)
based on the code of Version 1.6.20

It's not much to be changed back to make Freeswitch 1.10 work with Firefox, BUT unfortunately I do not understand everything.

In our case, Freeswitch is always the initiating agent that sends the INVITE message and therefore also the ICE-CONTROLLING agent.

I have attachted two PCAP screenshots to explain the differnt behavior (They have been captured on Freeswitch side)

In the first picture you can see that the browser sends binding requests, which are also answered correctly by Freeswitch. However, Freeswitch itself does not send binding requests, although it is the controlling agent.

![fs_1 10_firefox_ice_check_failed](https://user-images.githubusercontent.com/2076084/90513445-f6624700-e15f-11ea-9c59-3056bc032442.png)

This is a PCAP, with a patched freeswitch. Here Freeswitch also sends binding requests (which it must do by default). As soon as Firefox receives these and sees the USE-CANDIDATE flag, it starts the DTLS negotiation.

![fs_1 10_firefox_ice_check_ok](https://user-images.githubusercontent.com/2076084/90513797-7dafba80-e160-11ea-87c7-c5be40be105e.png)

Since Freeswitch has the role of ICE-CONTROLLING, he is responsible for the candidate nomination. Since version 1.8 he does not do this anymore on the basis of PRFLX candidates.

What is the reason you changed this?

**Comment by markose** [comment]
This is the patch that makes Firefox and Freeswitch work without STUN server. As I said, it is completely taken over from Freeswitch 1.6.20 and was in my opinion the correct behaviour.

```diff
--- switch_rtp.c	2020-08-17 13:41:51.905853818 +0200
+++ merged_switch_rtp.c	2020-08-17 14:00:34.588387121 +0200
@@ -1218,8 +1218,6 @@
 			uint8_t do_adj = 0;
 			switch_time_t now = switch_micro_time_now();
 			int cmp = 0;
-			int cur_idx = -1;//, is_relay = 0;
-			int i;
 			
 			if (is_rtcp) {
 				from_addr = rtp_session->rtcp_from_addr;
@@ -1273,43 +1271,46 @@
 				if (!do_adj) {
 					rtp_session->wrong_addrs++;
 				}
-
-				for (i = 0; i < ice->ice_params->cand_idx[ice->proto]; i++) {
-					if (!strcmp(ice->ice_params->cands[i][ice->proto].con_addr, host)) {
-						cur_idx = i;
-						//if (!strcasecmp(ice->ice_params->cands[i][ice->proto].cand_type, "relay")) {
-						//	is_relay = 1;
-						//}
-					}
-				}
-				
-				
-				if (ice->ice_params && ice->ice_params->cands[ice->ice_params->chosen[ice->proto]][ice->proto].cand_type &&
-					!strcasecmp(ice->ice_params->cands[ice->ice_params->chosen[ice->proto]][ice->proto].cand_type, "relay")) {
-					do_adj++;
-				}
 			}
 			
 			if ((ice->type & ICE_VANILLA) && ice->ice_params && do_adj) {
+				int i = 0;
+
 				ice->missed_count = 0;
 				ice->rready = 1;
 
-				if (cur_idx > -1) {
-					ice->ice_params->chosen[ice->proto] = cur_idx;
+				for (i = 0; i < ice->ice_params->cand_idx[ice->proto]; i++) {
+					if (ice->ice_params->cands[i][ice->proto].con_port == port) {
+						if (!strcmp(ice->ice_params->cands[i][ice->proto].con_addr, host) &&
+							ice->ice_params->cands[i][ice->proto].cand_type &&
+							!strcmp(ice->ice_params->cands[i][ice->proto].cand_type, "relay")) {
+
+							if (elapsed < 1000) {
+								switch_log_printf(SWITCH_CHANNEL_SESSION_LOG(rtp_session->session), SWITCH_LOG_WARNING,
+												  "Skiping RELAY stun/%s/dtls port change from %s:%u to %s:%u\n", is_rtcp ? "rtcp" : "rtp",
+												  host2, port2,
+												  host, port);
+
+								goto end;
+							}
+
+							break;
+						}
+					}
 				}
-				
+
 				switch_log_printf(SWITCH_CHANNEL_SESSION_LOG(rtp_session->session), SWITCH_LOG_NOTICE,
-								  "Auto Changing %s stun/%s/dtls port from %s:%u to %s:%u idx:%d\qn", rtp_type(rtp_session), is_rtcp ? "rtcp" : "rtp",
+								  "Auto Changing %s stun/%s/dtls port from %s:%u to %s:%u\n", rtp_type(rtp_session), is_rtcp ? "rtcp" : "rtp",
 								  host2, port2,
-								  host, port, cur_idx);
+								  host, port);
 
 				switch_rtp_change_ice_dest(rtp_session, ice, host, port);
 				ice->last_ok = now;
 				rtp_session->wrong_addrs = 0;
 			}
-			//if (cmp) {
-			switch_socket_sendto(sock_output, from_addr, 0, (void *) rpacket, &bytes);
-			//}
+			if (cmp) {
+				switch_socket_sendto(sock_output, from_addr, 0, (void *) rpacket, &bytes);
+			}
 		}
 	} else if (packet->header.type == SWITCH_STUN_BINDING_ERROR_RESPONSE) {
 

```
