### ISSUE TITLE
[ICE] Changing RTP/STUN/DTLS port on first binding request from remote peer

### ISSUE THREAD

**Issue by markose** [signalwire/freeswitch#811]
Currently the RTP/STUN/DTLS port is changed after 4 binding requests from remote peer.

A faster change, e.g. after 2 or 1 binding requests, would improve interoperability with Firefox, which only sends a few binding requests and then aborts the ICE process.

Unfortunately this makes it impossible to use Firefox behind NAT without an additional STUN server.

Reducing the number of binding requests to receive would speed up the WebRTC setup significantly.

In https://github.com/signalwire/freeswitch/issues/751#issuecomment-675461014 I have uploaded a screenshot of a PCAP that shows the problem. Here you can see that the process is stopped because Freeswitch (as ICE-CONTROLLING agent) does not send a binding request.

What is the reason for waiting 4 binding requests until the media IP/port is changed?

**Comment by mjerris** [comment]
if you want to create an actual pull request we can review, but we dont change right away to avoid flapping back and forth between candidates and that is intentional.  The correct solution as i said on the other issue is to properly configure stun/turn so that proper candidates are returned from the client in the first place.  we can not change it to 1 request causing auto-adjust because it will cause constant flapping back and forth between multiple candidates.
