### ISSUE TITLE
Audio played with uuid_displace on call is not recorded.

### ISSUE THREAD

**Issue by Alconqro** [signalwire/freeswitch#82]
I have been debugging this and all point to a bug.

When we record a call not all the audio on the channel is recorded, all the media from the remote side is heard and recorded fine, but the media we play on the channel using the command uuid_displace is heard by the remote side but not recorded.

I already test with different codecs, record on different formats (wav, mp3 & ogg), play audio files on different formats too, using the record_session on the dialplan or on the origination command, recording on mono and stereo, confirming the RECORD_WRITE_ONLY and RECORD_READ_ONLY are disabled, and all the time the uuid_displace file is played but not recorded.

Other commands to play audio files (uuid_broadcast, moh, etc.) works fine and are recorded.

This is working fine in the version 1.6.20 but not on the 1.10.1

Attached is a file with the FS log when we make a test (CLI), on this test the audio files where played fine, but on the recording only the uuid_broadcast was recorded.

[FS_log_debug_191029.log](https://github.com/signalwire/freeswitch/files/3785417/FS_log_debug_191029.log)

**Comment by mjerris** [comment]
the ordering of the media bugs is important to the behavior here.  it can work either way based on the order you attach the bugs.

**Comment by Sp0rN** [comment]
@briankwest 

I just came across this issue, as it is the reason behind my question here: 

https://github.com/signalwire/freeswitch/issues/513

Essentially we were trying to create a workaround for this exact problem, not knowing it was a possible bug, but just behaviour of uuid_displace. Essentially we are experiencing this exact same issue, using uuid_displace to play a tone_stream, that is never in the recording, but is present during the call.

Is there any way we can assist in resolving this?

**Comment by Sp0rN** [comment]
Hi Guys,

Any feedback here or possible workarounds?

**Comment by Sp0rN** [comment]
Hi Guys, Is there anything I can provide here to help with investigations?

**Comment by Kick1911** [comment]
I was reading through the code as well as testing and found that there are 2 new flags that have been added since v1.6. Namely `f` and `w`.

In [v1.10](https://github.com/signalwire/freeswitch/blob/f7bdd3845a91c77ff6c776a70ae2fc9d7f7d3f86/src/switch_core_media_bug.c#L978): The `f` flag adds a bug_flag `SMBF_FIRST` which runs the following code in function `switch_code_media_bug_add`:
```
if (!added && switch_test_flag(bug, SMBF_FIRST)) {
	bug->next = session->bugs;
	session->bugs = bug;
	added = 1;
}
```

In [v1.6](https://github.com/signalwire/freeswitch/blob/43a9feb7f8705af5008c963e36e36b9b1d69c373/src/switch_core_media_bug.c#L947) this code was unconditional(ran all the time).

I have tried the `f` flag and was able to hear the playback in the recording from the right ear.
If it is not what you want, flags `rw` together have also worked for me.

NOTE: you must have a `limit` in the `uuid_displace` command. You can use 0 to indicate no limit.

**Comment by crienzo** [comment]
Set `f` flag on displace to make it execute on the frame before recording saves it.
