### ISSUE TITLE
Failed to start freeswitch

### ISSUE THREAD

**Issue by ducth-THD** [signalwire/freeswitch#83]
I'm a newbie with freeswitch. 
I'm getting this error when installing freeswitch

root@debian-asdf:~# systemctl status freeswitch.service
● freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-10-30 22:07:30 +07; 20min ago
  Process: 952 ExecStart=/usr/bin/freeswitch -u ${USER} -g ${GROUP} -ncwait ${DAEMON_OPTS} (code=exited, status=1/FAILURE)
  Process: 949 ExecStartPre=/bin/chown -R ${USER}:${GROUP} /var/lib/freeswitch /var/log/freeswitch /etc/freeswitch /usr/share/fr

Oct 30 22:07:30 debian-asdf systemd[1]: freeswitch.service: Control process exited, code=exited status=1
Oct 30 22:07:30 debian-asdf systemd[1]: Failed to start freeswitch.
Oct 30 22:07:30 debian-asdf systemd[1]: freeswitch.service: Unit entered failed state.
Oct 30 22:07:30 debian-asdf systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Oct 30 22:07:30 debian-asdf systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Oct 30 22:07:30 debian-asdf systemd[1]: Stopped freeswitch.
Oct 30 22:07:30 debian-asdf systemd[1]: freeswitch.service: Start request repeated too quickly.
Oct 30 22:07:30 debian-asdf systemd[1]: Failed to start freeswitch.
Oct 30 22:07:30 debian-asdf systemd[1]: freeswitch.service: Unit entered failed state.
Oct 30 22:07:30 debian-asdf systemd[1]: freeswitch.service: Failed with result 'exit-code'.

Can you help me?
root@debian-asdf:~# uname -a
Linux debian-asdf 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

**Comment by cdosoftei** [comment]
Can you share the output of
```sh
sudo journalctl -u freeswitch
```
as well as the contents of `/var/log/freeswitch/freeswitch.log`?

**Comment by ducth-THD** [comment]
HI,
below is the output

root@debian-asdf:~# journalctl -u freeswitch
-- Logs begin at Thu 2019-10-31 07:33:03 +07, end at Thu 2019-10-31 07:36:53 +07. --
Oct 31 07:33:06 debian-asdf systemd[1]: Starting freeswitch...
Oct 31 07:33:06 debian-asdf freeswitch[866]: 869 Backgrounding.
Oct 31 07:33:06 debian-asdf freeswitch[866]: FreeSWITCH[866] Error starting system! pid:869
Oct 31 07:33:06 debian-asdf systemd[1]: freeswitch.service: Control process exited, code=exited status=1
Oct 31 07:33:06 debian-asdf systemd[1]: Failed to start freeswitch.
Oct 31 07:33:06 debian-asdf systemd[1]: freeswitch.service: Unit entered failed state.
Oct 31 07:33:06 debian-asdf systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Oct 31 07:33:06 debian-asdf systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Oct 31 07:33:06 debian-asdf systemd[1]: Stopped freeswitch.
Oct 31 07:33:06 debian-asdf systemd[1]: Starting freeswitch...
Oct 31 07:33:07 debian-asdf freeswitch[954]: 960 Backgrounding.
Oct 31 07:33:07 debian-asdf freeswitch[954]: FreeSWITCH[954] Error starting system! pid:960
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Control process exited, code=exited status=1
Oct 31 07:33:07 debian-asdf systemd[1]: Failed to start freeswitch.
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Unit entered failed state.
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Oct 31 07:33:07 debian-asdf systemd[1]: Stopped freeswitch.
Oct 31 07:33:07 debian-asdf systemd[1]: Starting freeswitch...
Oct 31 07:33:07 debian-asdf freeswitch[1037]: 1039 Backgrounding.
Oct 31 07:33:07 debian-asdf freeswitch[1037]: FreeSWITCH[1037] Error starting system! pid:1039
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Control process exited, code=exited status=1
Oct 31 07:33:07 debian-asdf systemd[1]: Failed to start freeswitch.
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Unit entered failed state.
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Oct 31 07:33:07 debian-asdf systemd[1]: Stopped freeswitch.
Oct 31 07:33:07 debian-asdf systemd[1]: Starting freeswitch...
Oct 31 07:33:07 debian-asdf freeswitch[1045]: 1047 Backgrounding.
Oct 31 07:33:07 debian-asdf freeswitch[1045]: FreeSWITCH[1045] Error starting system! pid:1047
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Control process exited, code=exited status=1
Oct 31 07:33:07 debian-asdf systemd[1]: Failed to start freeswitch.
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Unit entered failed state.
Oct 31 07:33:07 debian-asdf systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Oct 31 07:33:08 debian-asdf systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Oct 31 07:33:08 debian-asdf systemd[1]: Stopped freeswitch.
Oct 31 07:33:08 debian-asdf systemd[1]: Starting freeswitch...
Oct 31 07:33:08 debian-asdf freeswitch[1053]: 1055 Backgrounding.
Oct 31 07:33:08 debian-asdf freeswitch[1053]: FreeSWITCH[1053] Error starting system! pid:1055
Oct 31 07:33:08 debian-asdf systemd[1]: freeswitch.service: Control process exited, code=exited status=1
Oct 31 07:33:08 debian-asdf systemd[1]: Failed to start freeswitch.
Oct 31 07:33:08 debian-asdf systemd[1]: freeswitch.service: Unit entered failed state.
Oct 31 07:33:08 debian-asdf systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Oct 31 07:33:08 debian-asdf systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Oct 31 07:33:08 debian-asdf systemd[1]: Stopped freeswitch.
Oct 31 07:33:08 debian-asdf systemd[1]: freeswitch.service: Start request repeated too quickly.
Oct 31 07:33:08 debian-asdf systemd[1]: Failed to start freeswitch.
Oct 31 07:33:08 debian-asdf systemd[1]: freeswitch.service: Unit entered failed state.
Oct 31 07:33:08 debian-asdf systemd[1]: freeswitch.service: Failed with result 'exit-code'.
lines 15-50/50 (END)


It don't have freeswitch logs. only 1 file but it do'n have any content.
root@debian-asdf:/var/log/freeswitch# ls -l
total 0
-rw-rw---- 1 freeswitch freeswitch 0 Oct 31 07:33 freeswitch.xml.fsxml.tmp
root@debian-asdf:/var/log/freeswitch#
root@debian-asdf:/var/log/freeswitch# cat freeswitch.xml.fsxml.tmp
root@debian-asdf:/var/log/freeswitch#

Thanks,

**Comment by jungle-boogie** [comment]
Can you start freeswitch in the foreground?

**Comment by jungle-boogie** [comment]
How was freeswitch installed - src or package?

**Comment by ducth-THD** [comment]
Hi Jungle-boogie,

I managed to resolve this issue, I just reinstall and it has been resolve.
Thank for your help.

**Comment by jilenloa** [comment]
For me on debian 9, installing the following package resolved it.

apt-get install libopenmpt0

**Comment by olubiyi95** [comment]
hello please i need help. my freeswitch keeps crashing no matter the linux debian os i use. i have tried debian 8,9,and now 10 and FS keeps doing the same over and over again. i have tried getting this fixed permanently but no solution yet. FS was working fine on debian 10 and then it stopped. getting this error 
Job for freeswitch.service failed because the control process exited with error code.
See "systemctl status freeswitch.service" and "journalctl -xe" for details.
and this is what systemctl status freeswitch.service says 
 freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; vendor preset: enab
   Active: failed (Result: exit-code) since Tue 2021-04-13 15:45:34 PDT; 10min ago
  Process: 9493 ExecStartPre=/bin/chown -R ${USER}:${GROUP} /var/lib/freeswitch /var/lo
  Process: 9494 ExecStart=/usr/bin/freeswitch -u ${USER} -g ${GROUP} -ncwait ${DAEMON_O

Apr 13 15:45:34 oluga systemd[1]: freeswitch.service: Control process exited, code=exit
Apr 13 15:45:34 oluga systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Apr 13 15:45:34 oluga systemd[1]: Failed to start freeswitch.
Apr 13 15:45:34 oluga systemd[1]: freeswitch.service: Service RestartSec=100ms expired,
Apr 13 15:45:34 oluga systemd[1]: freeswitch.service: Scheduled restart job, restart co
Apr 13 15:45:34 oluga systemd[1]: Stopped freeswitch.
Apr 13 15:45:34 oluga systemd[1]: freeswitch.service: Start request repeated too quickl
Apr 13 15:45:34 oluga systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Apr 13 15:45:34 oluga systemd[1]: Failed to start freeswitch.

and this is journalctl
Logs begin at Tue 2021-04-13 11:29:53 PDT, end at Tue 2021-04-13 15:52:56 PDT. --
Apr 13 11:29:53 oluga kernel: Linux version 4.19.0-16-amd64 (debian-kernel@lists.debian
Apr 13 11:29:53 oluga kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-4.19.0-16-amd64 ro
Apr 13 11:29:53 oluga kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating po
Apr 13 11:29:53 oluga kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Apr 13 11:29:53 oluga kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Apr 13 11:29:53 oluga kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Apr 13 11:29:53 oluga kernel: x86/fpu: Enabled xstate features 0x7, context size is 832
Apr 13 11:29:53 oluga kernel: BIOS-provided physical RAM map:
Apr 13 11:29:53 oluga kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] us
Apr 13 11:29:53 oluga kernel: BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] re
Apr 13 11:29:53 oluga kernel: BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] re
Apr 13 11:29:53 oluga kernel: BIOS-e820: [mem 0x0000000000100000-0x000000007ffeffff] us
Apr 13 11:29:53 oluga kernel: BIOS-e820: [mem 0x000000007fff0000-0x000000007fffffff] AC
Apr 13 11:29:53 oluga kernel: BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] re
Apr 13 11:29:53 oluga kernel: BIOS-e820: [mem 0x00000000fee00000-0x00000000fee00fff] re
Apr 13 11:29:53 oluga kernel: BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] re
Apr 13 11:29:53 oluga kernel: NX (Execute Disable) protection: active
Apr 13 11:29:53 oluga kernel: SMBIOS 2.5 present.
Apr 13 11:29:53 oluga kernel: DMI: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 
Apr 13 11:29:53 oluga kernel: Hypervisor detected: KVM
Apr 13 11:29:53 oluga kernel: kvm-clock: Using msrs 4b564d01 and 4b564d00
Apr 13 11:29:53 oluga kernel: kvm-clock: cpu 0, msr 17fec001, primary cpu clock
Apr 13 11:29:53 oluga kernel: kvm-clock: using sched offset of 9185747233 cycles
Apr 13 11:29:53 oluga kernel: clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycl
Apr 13 11:29:53 oluga kernel: tsc: Detected 1992.001 MHz processor
Apr 13 11:29:53 oluga kernel: e820: update [mem 0x00000000-0x00000fff] usable ==> reser
Apr 13 11:29:53 oluga kernel: e820: remove [mem 0x000a0000-0x000fffff] usable
Apr 13 11:29:53 oluga kernel: last_pfn = 0x7fff0 max_arch_pfn = 0x400000000
Apr 13 11:29:53 oluga kernel: MTRR default type: uncachable
lines 1-30

please what do i do to solve this once and for all ? it's really frustrating
