### ISSUE TITLE
Ubuntu installation steps?

### ISSUE THREAD

**Issue by pgenderson** [signalwire/freeswitch#840]
I tried follow the Debian steps on Ubuntu Server 20.04.1 (don't know any better):

```
    $ sudo wget -O - https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc | apt-key add -

    --2020-09-01 23:31:46--  https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc
    Resolving files.freeswitch.org (files.freeswitch.org)... 190.102.98.174, 2803:d000:fffe::174
    Connecting to files.freeswitch.org (files.freeswitch.org)|190.102.98.174|:443... E: This command can only be used by root.
    connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 3155 (3.1K) [text/plain]
    Saving to: ‘STDOUT’

    -                               0%[                                               ]       0  --.-KB/s    in 0s


    Cannot write to ‘-’ (Success).```

**Comment by andywolk** [comment]
Try not using pipes:
```
wget https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc
apt-key add fsstretch-archive-keyring.asc
```

**Comment by mjerris** [comment]
the core freeswitch team does not maintain ubuntu packaging for freeswitch and we have no plans on doing so.  if the community is interested in doing so we are happy to host documents on the wiki and packaging repositories.  This would require a committed maintainer with the skills to handle all the porting and packaging tasks involved and i would expect it to take a significant initial time commitment.  If anyone has the skills and willingness to do this they can contact me by email at mike@signalwire.com and i can help
provide some guidance on the task, otherwise andrey’s  comment above and the archived docs for ubuntu are the best guides but they are for sure incomplete and will not get you a working build.

**Comment by wangqingwen** [comment]
How to compile the project on ubuntu os? I'm no't found the makefile in project code.
